In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv('dataset/Algerian_forest_fires_dataset.csv')
df

day month  year Temperature  RH  Ws Rain   FFMC  DMC    DC  ISI   BUI  \
0     1     6  2012          29  57  18     0  65.7  3.4   7.6  1.3   3.4   
1     2     6  2012          29  61  13   1.3  64.4  4.1   7.6    1   3.9   
2     3     6  2012          26  82  22  13.1  47.1  2.5   7.1  0.3   2.7   
3     4     6  2012          25  89  13   2.5  28.6  1.3   6.9    0   1.7   
4     5     6  2012          27  77  16     0  64.8    3  14.2  1.2   3.9   
..   ..   ...   ...         ...  ..  ..   ...   ...  ...   ...  ...   ...   
242  26     9  2012          30  65  14     0  85.4   16  44.5  4.5  16.9   
243  27     9  2012          28  87  15   4.4  41.1  6.5     8  0.1   6.2   
244  28     9  2012          27  87  29   0.5  45.9  3.5   7.9  0.4   3.4   
245  29     9  2012          24  54  18   0.1  79.7  4.3  15.2  1.7   5.1   
246  30     9  2012          24  64  15   0.2  67.3  3.8  16.5  1.2   4.8   

     FWI     Classes    
0    0.5   not fire     
1    0.4   not fire     
2    0.1   not fire     
3      0   not fire     
4    0.5   not fire     
..   ...           ...  
242  6.5       fire     
243    0   not fire     
244  0.2   not fire     
245  0.7   not fire     
246  0.5  not fire      

[247 rows x 14 columns]

In [4]:
df.shape

(247, 14)

In [5]:
df.isnull().sum()

day            1
month          2
year           2
Temperature    2
 RH            2
 Ws            2
Rain           2
FFMC           2
DMC            2
DC             2
ISI            2
BUI            2
FWI            2
Classes        3
dtype: int64

In [6]:
df[df.isnull().any(axis=1)]

day month  year Temperature   RH   Ws Rain   \
122                            NaN   NaN   NaN         NaN  NaN  NaN   NaN   
123  Sidi-Bel Abbes Region Dataset   NaN   NaN         NaN  NaN  NaN   NaN   
168                             14     7  2012          37   37   18   0.2   

     FFMC   DMC      DC   ISI   BUI      FWI Classes    
122   NaN   NaN     NaN   NaN   NaN      NaN       NaN  
123   NaN   NaN     NaN   NaN   NaN      NaN       NaN  
168  88.9  12.9  14.6 9  12.5  10.4  fire          NaN

In [7]:
df.dropna(inplace=True)
df

day month  year Temperature  RH  Ws Rain   FFMC  DMC    DC  ISI   BUI  \
0     1     6  2012          29  57  18     0  65.7  3.4   7.6  1.3   3.4   
1     2     6  2012          29  61  13   1.3  64.4  4.1   7.6    1   3.9   
2     3     6  2012          26  82  22  13.1  47.1  2.5   7.1  0.3   2.7   
3     4     6  2012          25  89  13   2.5  28.6  1.3   6.9    0   1.7   
4     5     6  2012          27  77  16     0  64.8    3  14.2  1.2   3.9   
..   ..   ...   ...         ...  ..  ..   ...   ...  ...   ...  ...   ...   
242  26     9  2012          30  65  14     0  85.4   16  44.5  4.5  16.9   
243  27     9  2012          28  87  15   4.4  41.1  6.5     8  0.1   6.2   
244  28     9  2012          27  87  29   0.5  45.9  3.5   7.9  0.4   3.4   
245  29     9  2012          24  54  18   0.1  79.7  4.3  15.2  1.7   5.1   
246  30     9  2012          24  64  15   0.2  67.3  3.8  16.5  1.2   4.8   

     FWI     Classes    
0    0.5   not fire     
1    0.4   not fire     
2    0.1   not fire     
3      0   not fire     
4    0.5   not fire     
..   ...           ...  
242  6.5       fire     
243    0   not fire     
244  0.2   not fire     
245  0.7   not fire     
246  0.5  not fire      

[244 rows x 14 columns]

In [8]:
df.shape

(244, 14)

In [9]:
df.isnull().sum()

day            0
month          0
year           0
Temperature    0
 RH            0
 Ws            0
Rain           0
FFMC           0
DMC            0
DC             0
ISI            0
BUI            0
FWI            0
Classes        0
dtype: int64

In [10]:
df['Classes  '].unique()

array(['not fire   ', 'fire   ', 'fire', 'fire ', 'not fire', 'not fire ',
       'Classes  ', 'not fire     ', 'not fire    '], dtype=object)

In [11]:
df['cleaned_classes']=df['Classes  '].str.strip()

In [12]:
df['cleaned_classes'].unique()

array(['not fire', 'fire', 'Classes'], dtype=object)

In [13]:
df.shape

(244, 15)

In [14]:
df.drop(df[df['Classes  '].str.strip()=='Classes'].index,inplace=True)

In [15]:
df.shape

(243, 15)

In [16]:
df.head()

day month  year Temperature  RH  Ws Rain   FFMC  DMC    DC  ISI  BUI  FWI  \
0   1     6  2012          29  57  18     0  65.7  3.4   7.6  1.3  3.4  0.5   
1   2     6  2012          29  61  13   1.3  64.4  4.1   7.6    1  3.9  0.4   
2   3     6  2012          26  82  22  13.1  47.1  2.5   7.1  0.3  2.7  0.1   
3   4     6  2012          25  89  13   2.5  28.6  1.3   6.9    0  1.7    0   
4   5     6  2012          27  77  16     0  64.8    3  14.2  1.2  3.9  0.5   

     Classes   cleaned_classes  
0  not fire           not fire  
1  not fire           not fire  
2  not fire           not fire  
3  not fire           not fire  
4  not fire           not fire

In [18]:
df.columns

Index(['day', 'month', 'year', 'Temperature', ' RH', ' Ws', 'Rain ', 'FFMC',
       'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes  ', 'cleaned_classes'],
      dtype='object')

In [19]:
df.drop('Classes  ',axis=1,inplace=True)

In [20]:
df.head()

day month  year Temperature  RH  Ws Rain   FFMC  DMC    DC  ISI  BUI  FWI  \
0   1     6  2012          29  57  18     0  65.7  3.4   7.6  1.3  3.4  0.5   
1   2     6  2012          29  61  13   1.3  64.4  4.1   7.6    1  3.9  0.4   
2   3     6  2012          26  82  22  13.1  47.1  2.5   7.1  0.3  2.7  0.1   
3   4     6  2012          25  89  13   2.5  28.6  1.3   6.9    0  1.7    0   
4   5     6  2012          27  77  16     0  64.8    3  14.2  1.2  3.9  0.5   

  cleaned_classes  
0        not fire  
1        not fire  
2        not fire  
3        not fire  
4        not fire

In [32]:
df['FWI'].unique()

array(['0.5', '0.4', '0.1', '0', '2.5', '7.2', '7.1', '0.3', '0.9', '5.6',
       '0.2', '1.4', '2.2', '2.3', '3.8', '7.5', '8.4', '10.6', '15',
       '13.9', '3.9', '12.9', '1.7', '4.9', '6.8', '3.2', '8', '0.6',
       '3.4', '0.8', '3.6', '6', '10.9', '4', '8.8', '2.8', '2.1', '1.3',
       '7.3', '15.3', '11.3', '11.9', '10.7', '15.7', '6.1', '2.6', '9.9',
       '11.6', '12.1', '4.2', '10.2', '6.3', '14.6', '16.1', '17.2',
       '16.8', '18.4', '20.4', '22.3', '20.9', '20.3', '13.7', '13.2',
       '19.9', '30.2', '5.9', '7.7', '9.7', '8.3', '0.7', '4.1', '1',
       '3.1', '1.9', '10', '16.7', '1.2', '5.3', '6.7', '9.5', '12',
       '6.4', '5.2', '3', '9.6', '4.7', '14.1', '9.1', '13', '17.3', '30',
       '25.4', '16.3', '9', '14.5', '13.5', '19.5', '12.6', '12.7',
       '21.6', '18.8', '10.5', '5.5', '14.8', '24', '26.3', '12.2',
       '18.1', '24.5', '26.9', '31.1', '30.3', '26.1', '16', '19.4',
       '2.7', '3.7', '10.3', '5.7', '9.8', '19.3', '17.5', '15.4', '15.2',
  

In [35]:
df.columns

Index(['day', 'month', 'year', 'Temperature', ' RH', ' Ws', 'Rain ', 'FFMC',
       'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'cleaned_classes'],
      dtype='object')

In [39]:
X=df.drop('cleaned_classes',axis=1)
y=df['cleaned_classes']
X

day month  year Temperature  RH  Ws Rain   FFMC  DMC    DC  ISI   BUI  FWI
0     1     6  2012          29  57  18     0  65.7  3.4   7.6  1.3   3.4  0.5
1     2     6  2012          29  61  13   1.3  64.4  4.1   7.6    1   3.9  0.4
2     3     6  2012          26  82  22  13.1  47.1  2.5   7.1  0.3   2.7  0.1
3     4     6  2012          25  89  13   2.5  28.6  1.3   6.9    0   1.7    0
4     5     6  2012          27  77  16     0  64.8    3  14.2  1.2   3.9  0.5
..   ..   ...   ...         ...  ..  ..   ...   ...  ...   ...  ...   ...  ...
242  26     9  2012          30  65  14     0  85.4   16  44.5  4.5  16.9  6.5
243  27     9  2012          28  87  15   4.4  41.1  6.5     8  0.1   6.2    0
244  28     9  2012          27  87  29   0.5  45.9  3.5   7.9  0.4   3.4  0.2
245  29     9  2012          24  54  18   0.1  79.7  4.3  15.2  1.7   5.1  0.7
246  30     9  2012          24  64  15   0.2  67.3  3.8  16.5  1.2   4.8  0.5

[243 rows x 13 columns]

In [42]:
X.corr()

day     month  year  Temperature        RH        Ws  \
day          1.000000 -0.000369   NaN     0.097227 -0.076034  0.047812   
month       -0.000369  1.000000   NaN    -0.056781 -0.041252 -0.039880   
year              NaN       NaN   NaN          NaN       NaN       NaN   
Temperature  0.097227 -0.056781   NaN     1.000000 -0.651400 -0.284510   
 RH         -0.076034 -0.041252   NaN    -0.651400  1.000000  0.244048   
 Ws          0.047812 -0.039880   NaN    -0.284510  0.244048  1.000000   
Rain        -0.112523  0.034822   NaN    -0.326492  0.222356  0.171506   
FFMC         0.224956  0.017030   NaN     0.676568 -0.644873 -0.166548   
DMC          0.491514  0.067943   NaN     0.485687 -0.408519 -0.000721   
DC           0.527952  0.126511   NaN     0.376284 -0.226941  0.079135   
ISI          0.180543  0.065608   NaN     0.603871 -0.686667  0.008532   
BUI          0.517117  0.085073   NaN     0.459789 -0.353841  0.031438   
FWI          0.350781  0.082639   NaN     0.566670 -0.580957  0.032368   

                Rain       FFMC       DMC        DC       ISI       BUI  \
day         -0.112523  0.224956  0.491514  0.527952  0.180543  0.517117   
month        0.034822  0.017030  0.067943  0.126511  0.065608  0.085073   
year              NaN       NaN       NaN       NaN       NaN       NaN   
Temperature -0.326492  0.676568  0.485687  0.376284  0.603871  0.459789   
 RH          0.222356 -0.644873 -0.408519 -0.226941 -0.686667 -0.353841   
 Ws          0.171506 -0.166548 -0.000721  0.079135  0.008532  0.031438   
Rain         1.000000 -0.543906 -0.288773 -0.298023 -0.347484 -0.299852   
FFMC        -0.543906  1.000000  0.603608  0.507397  0.740007  0.592011   
DMC         -0.288773  0.603608  1.000000  0.875925  0.680454  0.982248   
DC          -0.298023  0.507397  0.875925  1.000000  0.508643  0.941988   
ISI         -0.347484  0.740007  0.680454  0.508643  1.000000  0.644093   
BUI         -0.299852  0.592011  0.982248  0.941988  0.644093  1.000000   
FWI         -0.324422  0.691132  0.875864  0.739521  0.922895  0.857973   

                  FWI  
day          0.350781  
month        0.082639  
year              NaN  
Temperature  0.566670  
 RH         -0.580957  
 Ws          0.032368  
Rain        -0.324422  
FFMC         0.691132  
DMC          0.875864  
DC           0.739521  
ISI          0.922895  
BUI          0.857973  
FWI          1.000000

In [52]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [53]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [54]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
X_train_scaled=ss.fit_transform(X_train)
X_test_scaled=ss.transform(X_test)

In [55]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier

In [56]:
classification_models={
    "Logistic Regression":LogisticRegression(),
    "DecisionTreeClassifier":DecisionTreeClassifier(),
    "RandomForestClassifier":RandomForestClassifier(),
    "KNeighborsClassifier":KNeighborsClassifier(),
    "SVC":SVC(),
    "XGBClassifier":XGBClassifier()
}

In [57]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
import warnings
warnings.filterwarnings('ignore')
for name, model in classification_models.items():
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)
    
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, average='weighted')
    rec = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')
    
    print(f"{name}:")
    print(f"Accuracy: {acc:.4f} | Precision: {prec:.4f} | Recall: {rec:.4f} | F1-score: {f1:.4f}")
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))
    print("-"*50)


Logistic Regression:
Accuracy: 0.9592 | Precision: 0.9592 | Recall: 0.9592 | F1-score: 0.9592
Confusion Matrix:
[[26  1]
 [ 1 21]]
--------------------------------------------------
DecisionTreeClassifier:
Accuracy: 1.0000 | Precision: 1.0000 | Recall: 1.0000 | F1-score: 1.0000
Confusion Matrix:
[[27  0]
 [ 0 22]]
--------------------------------------------------
RandomForestClassifier:
Accuracy: 0.9796 | Precision: 0.9805 | Recall: 0.9796 | F1-score: 0.9796
Confusion Matrix:
[[26  1]
 [ 0 22]]
--------------------------------------------------
KNeighborsClassifier:
Accuracy: 0.9184 | Precision: 0.9184 | Recall: 0.9184 | F1-score: 0.9184
Confusion Matrix:
[[25  2]
 [ 2 20]]
--------------------------------------------------
SVC:
Accuracy: 0.9184 | Precision: 0.9184 | Recall: 0.9184 | F1-score: 0.9184
Confusion Matrix:
[[25  2]
 [ 2 20]]
--------------------------------------------------
XGBClassifier:
Accuracy: 0.9796 | Precision: 0.9805 | Recall: 0.9796 | F1-score: 0.9796
Confusion M

In [58]:
from sklearn.model_selection import GridSearchCV, cross_val_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

# 1️⃣ Define parameter grids
rf_params = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 5, 10],
    'min_samples_split': [2, 5]
}

xgb_params = {
    'n_estimators': [50, 100],
    'max_depth': [3, 5],
    'learning_rate': [0.01, 0.1]
}

# 2️⃣ Train Random Forest with GridSearchCV
rf_grid = GridSearchCV(RandomForestClassifier(random_state=42), rf_params, cv=5, scoring='accuracy', n_jobs=-1)
rf_grid.fit(X_train_scaled, y_train)
print(f"✅ Best Random Forest Params: {rf_grid.best_params_}")

# 3️⃣ Train XGBoost with GridSearchCV
xgb_grid = GridSearchCV(
    XGBClassifier(use_label_encoder=False, eval_metric='mlogloss', random_state=42),
    xgb_params, cv=5, scoring='accuracy', n_jobs=-1
)
xgb_grid.fit(X_train_scaled, y_train)
print(f"✅ Best XGBoost Params: {xgb_grid.best_params_}")

# 4️⃣ Evaluate function
def evaluate_model(name, model):
    y_pred = model.predict(X_test_scaled)
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, average='weighted')
    rec = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')
    cm = confusion_matrix(y_test, y_pred)
    
    print(f"\n{name} Results:")
    print(f"Accuracy: {acc:.4f} | Precision: {prec:.4f} | Recall: {rec:.4f} | F1-score: {f1:.4f}")
    print("Confusion Matrix:\n", cm)
    print("\nClassification Report:\n", classification_report(y_test, y_pred))
    return acc, prec, rec, f1

# 5️⃣ Evaluate both
evaluate_model("Random Forest", rf_grid)
evaluate_model("XGBoost", xgb_grid)

# 6️⃣ Cross-validation on train data
rf_cv = cross_val_score(rf_grid.best_estimator_, X_train_scaled, y_train, cv=5, scoring='accuracy')
xgb_cv = cross_val_score(xgb_grid.best_estimator_, X_train_scaled, y_train, cv=5, scoring='accuracy')
print(f"\n✅ RF Cross-validated accuracy: {rf_cv.mean():.4f}")
print(f"✅ XGB Cross-validated accuracy: {xgb_cv.mean():.4f}")


✅ Best Random Forest Params: {'max_depth': None, 'min_samples_split': 2, 'n_estimators': 200}
✅ Best XGBoost Params: {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 50}

Random Forest Results:
Accuracy: 0.9796 | Precision: 0.9805 | Recall: 0.9796 | F1-score: 0.9796
Confusion Matrix:
 [[26  1]
 [ 0 22]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.96      0.98        27
           1       0.96      1.00      0.98        22

    accuracy                           0.98        49
   macro avg       0.98      0.98      0.98        49
weighted avg       0.98      0.98      0.98        49


XGBoost Results:
Accuracy: 0.9796 | Precision: 0.9805 | Recall: 0.9796 | F1-score: 0.9796
Confusion Matrix:
 [[26  1]
 [ 0 22]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.96      0.98        27
           1       0.96      1.00      0.98        22

    accuracy       

/Users/siddharthavadlakonda/Documents/PROJECTS/renew_forestfire/env/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [23:58:24] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/Users/siddharthavadlakonda/Documents/PROJECTS/renew_forestfire/env/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [23:58:24] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/Users/siddharthavadlakonda/Documents/PROJECTS/renew_forestfire/env/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [23:58:24] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/Users/siddharthavadlakonda/Documents/PROJECTS/renew_forestfire/env/lib/python3.9/site-packages/xgboost/core.py:158: UserWar


✅ RF Cross-validated accuracy: 0.9794
✅ XGB Cross-validated accuracy: 0.9741
